version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_prac1
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - distributed-network

  redis:
    image: redis:latest
    container_name: redis_prac1
    ports:
      - "6379:6379"
    networks:
      - distributed-network

# InsultService:
#   build:
#     context: dockerfiles
#     dockerfile: InsultService.dockerfile
#   container_name: InsultService_prac1
#   image: insultservice
#   environment:
#     - NODE_NAME=InsultService
#     - REDIS_HOST=redis
#     - RABBIT_HOST=rabbitmq
#   ports:
#     - "5000:5000"
#   depends_on:
#     - rabbitmq
#     - redis
#   networks:
#     - distributed-network
#
# client:
#   build:
#       context: dockerfiles
#       dockerfile: client.dockerfile
#   container_name: client_prac1
#   image: client
#   environment:
#     - NODE_NAME=client
#     - REDIS_HOST=redis
#     - RABBIT_HOST=rabbitmq
#   ports:
#     - "5001:5001"
#   depends_on:
#     - rabbitmq
#     - redis
#   networks:
#     - distributed-network
#   stdin_open: true
#   tty: true
#   command: [ "tail", "-f", "/dev/null" ]  # Keeps the container running
#
# networks:
#   distributed-network:
