version: '3.8'

services:
  #rabbitmq:
  #  image: rabbitmq:3-management
  #  container_name: rabbitmq_prac1
  #  ports:
  #    - "5672:5672"
  #    - "15672:15672"

  redis-node1:
    image: redis:latest
    container_name: redis-node1
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly no
    ports:
      - "7001:6379"
    networks:
      redis-net:
        ipv4_address: 172.28.0.2 # Assign a static IP

  redis-node2:
    image: redis:latest
    container_name: redis-node2
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly no
    ports:
      - "7002:6379"
    networks:
      redis-net:
        ipv4_address: 172.28.0.3 # Assign a static IP

  redis-node3:
    image: redis:latest
    container_name: redis-node3
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly no
    ports:
      - "7003:6379"
    networks:
      redis-net:
        ipv4_address: 172.28.0.4 # Assign a static IP

networks:
  redis-net:
    driver: bridge
    ipam: # IP Address Management
      config:
        - subnet: 172.28.0.0/16 # Define the subnet for your network