version: '3.8'

services:
  #rabbitmq:
  #  image: rabbitmq:3-management
  #  container_name: rabbitmq_prac1
  #  ports:
  #    - "5672:5672"
  #    - "15672:15672"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_prac1
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:latest
    container_name: redis_prac1
    ports:
      - "6379:6379"